org: f72e1c13062e4f45ad951530acf9e5a7
app: docker-selenium-lambda
service: docker-selenium-lambda

configValidationMode: error
frameworkVersion: ">=3"

provider:
  name: aws
  environment:
    TEST_ENV: ${param:TEST_ENV}
#  runtime: python3.12 - I don't think we need this since we're running a docker image
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

functions:
  demo:
    timeout: 60
    memorySize: 2048
    image:
      name: img
